### ISSUE TITLE
downloadFile()'s call to createWriteStream does not wait for 'open' event

### ISSUE THREAD

**Issue by alewang** [appium/appium-base-driver#48]
I've noticed in the [Node docs for WriteStream] specify an 'open' event to indicate when a writable stream is opened for writing. I believe that the [downloadFile](https://github.com/appium/appium-base-driver/blob/24cc2cdb618504d33aa3238d139c7d4b744e4e77/lib/helpers.js#line-65) function should Promisify the call to createWriteStream and then `await` on that Promise before continuing.

**Comment by imurchie** [comment]
The `createWriteStream` method is not promisifyable, since it does not conform to the node-style with a final callback (see [here](https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options)). The `WriteStream` returned ought to be writeable, and the `open` event just so that application programmers can do other stuff when the stream has opened.

Are you seeing errors related to this?

**Comment by alewang** [comment]
I checked my set-up a few more times, but it seems like I don't have any errors related to createWriteStream. I must have been thinking that writing to a WriteStream would lead to errors before the open event is fired off. This thinking probably just comes from being new to Node programming in general.

I'll go ahead and close this issue. 😛

**Comment by imurchie** [comment]
Streams are often confusing. And the API that doesn't involve callbacks is particularly so.
